//
// CreateRegistrationSettingsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateRegistrationSettingsRequest: Codable {

    public var venueId: Int
    public var registrationFields: [RegistrationSettingNoId]?

    public init(venueId: Int, registrationFields: [RegistrationSettingNoId]?) {
        self.venueId = venueId
        self.registrationFields = registrationFields
    }


}

