//
// CreateWaiverRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateWaiverRequest: Codable {

    public var venueId: Int
    public var name: String?
    public var waiverText: String?

    public init(venueId: Int, name: String?, waiverText: String?) {
        self.venueId = venueId
        self.name = name
        self.waiverText = waiverText
    }


}

