//
// CreateMinorWaiverDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateMinorWaiverDTO: Codable {

    public var guardianSignature: Data?
    public var minorCustId: Int
    public var guardianCustId: Int

    public init(guardianSignature: Data?, minorCustId: Int, guardianCustId: Int) {
        self.guardianSignature = guardianSignature
        self.minorCustId = minorCustId
        self.guardianCustId = guardianCustId
    }


}

