//
// RegistrationSettingsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RegistrationSettingsResponse: Codable {

    public var registrationFields: [RegistrationSettingNoId]?
    public var settings: [Setting]?
    public var waiverText: String?

    public init(registrationFields: [RegistrationSettingNoId]?, settings: [Setting]?, waiverText: String?) {
        self.registrationFields = registrationFields
        self.settings = settings
        self.waiverText = waiverText
    }
    
    public enum CodingKeys: String, CodingKey {
        case registrationFields
        case settings
        case waiverText
    }


}

