//
// RegistrationSettingNoId.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RegistrationSettingNoId: Codable {

    public var name: String?
    public var _required: Bool
    public var displayName: String?
    public var show: Bool

    public init(name: String?, _required: Bool, displayName: String?, show: Bool) {
        self.name = name
        self._required = _required
        self.displayName = displayName
        self.show = show
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case _required = "required"
        case displayName
        case show
    }


}

