//
// SaveSettingRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SaveSettingRequest: Codable {

    public var venueId: Int
    public var settingValue: String?
    public var settingName: String?

    public init(venueId: Int, settingValue: String?, settingName: String?) {
        self.venueId = venueId
        self.settingValue = settingValue
        self.settingName = settingName
    }


}

