//
// UpdateWaiverRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateWaiverRequest: Codable {

    public var venueId: Int
    public var waiverId: Int
    public var waiverText: String?

    public init(venueId: Int, waiverId: Int, waiverText: String?) {
        self.venueId = venueId
        self.waiverId = waiverId
        self.waiverText = waiverText
    }


}

