//
// UserPageWithoutId.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserPageWithoutId: Codable {

    public var name: String?
    public var route: String?
    public var displayName: String?

    public init(name: String?, route: String?, displayName: String?) {
        self.name = name
        self.route = route
        self.displayName = displayName
    }


}

