//
// UserInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserInfo: Codable {

    public var username: String?
    public var firstName: String?
    public var lastName: String?

    public init(username: String?, firstName: String?, lastName: String?) {
        self.username = username
        self.firstName = firstName
        self.lastName = lastName
    }


}

