//
// VenueWithPages.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VenueWithPages: Codable {

    public var venueId: Int
    public var organizationId: Int
    public var venueName: String?
    public var address: String?
    public var city: String?
    public var state: String?
    public var zip: String?
    public var createdDate: String?
    public var userPages: [UserPageWithoutId]?
    public var userInformation: UserInfo?

    public init(venueId: Int, organizationId: Int, venueName: String?, address: String?, city: String?, state: String?, zip: String?, createdDate: String?, userPages: [UserPageWithoutId]?, userInformation: UserInfo?) {
        self.venueId = venueId
        self.organizationId = organizationId
        self.venueName = venueName
        self.address = address
        self.city = city
        self.state = state
        self.zip = zip
        self.createdDate = createdDate
        self.userPages = userPages
        self.userInformation = userInformation
    }
}
