//
// WaiverResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WaiverResponse: Codable {

    public var waivers: [Waiver]?
    public var selectedWaiver: Waiver?

    public init(waivers: [Waiver]?, selectedWaiver: Waiver?) {
        self.waivers = waivers
        self.selectedWaiver = selectedWaiver
    }


}

