//
// Waiver.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Waiver: Codable {

    public var waiverId: Int
    public var venueId: Int
    public var name: String?
    public var waiverText: String?
    public var createdDate: Date

    public init(waiverId: Int, venueId: Int, name: String?, waiverText: String?, createdDate: Date) {
        self.waiverId = waiverId
        self.venueId = venueId
        self.name = name
        self.waiverText = waiverText
        self.createdDate = createdDate
    }


}

