//
// AuthAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class AuthAPI {
    /**

     - parameter model: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func authAuthenticate(model: AuthenticateModel, completion: @escaping ((_ data: URL?,_ error: Error?) -> Void)) {
        authAuthenticateWithRequestBuilder(model: model).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /authenticate
     - API Key:
       - type: apiKey Authorization 
       - name: JWT
     - examples: [{contentType=application/json, example=""}]
     
     - parameter model: (body)  

     - returns: RequestBuilder<URL> 
     */
    open class func authAuthenticateWithRequestBuilder(model: AuthenticateModel) -> RequestBuilder<URL> {
        let path = "/authenticate"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: model)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<URL>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
