//
// VenuesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class VenuesAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func venuesGetVenue(completion: @escaping ((_ data: [VenueWithPages]?,_ error: Error?) -> Void)) {
        venuesGetVenueWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /Venues
     - API Key:
       - type: apiKey Authorization 
       - name: JWT
     - examples: [{contentType=application/json, example=[ {
  "organizationId" : 6,
  "venueName" : "venueName",
  "zip" : "zip",
  "address" : "address",
  "createdDate" : "2000-01-23T04:56:07.000+00:00",
  "city" : "city",
  "venueId" : 0,
  "userInformation" : {
    "firstName" : "firstName",
    "lastName" : "lastName",
    "username" : "username"
  },
  "userPages" : [ {
    "route" : "route",
    "displayName" : "displayName",
    "name" : "name"
  }, {
    "route" : "route",
    "displayName" : "displayName",
    "name" : "name"
  } ],
  "state" : "state"
}, {
  "organizationId" : 6,
  "venueName" : "venueName",
  "zip" : "zip",
  "address" : "address",
  "createdDate" : "2000-01-23T04:56:07.000+00:00",
  "city" : "city",
  "venueId" : 0,
  "userInformation" : {
    "firstName" : "firstName",
    "lastName" : "lastName",
    "username" : "username"
  },
  "userPages" : [ {
    "route" : "route",
    "displayName" : "displayName",
    "name" : "name"
  }, {
    "route" : "route",
    "displayName" : "displayName",
    "name" : "name"
  } ],
  "state" : "state"
} ]}]

     - returns: RequestBuilder<[VenueWithPages]> 
     */
    open class func venuesGetVenueWithRequestBuilder() -> RequestBuilder<[VenueWithPages]> {
        let path = "/Venues"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[VenueWithPages]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
